apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-registry
  namespace: terraform-registry
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/terraform-registry-s3-access
