---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-registry-data
  namespace: terraform-registry
  annotations:
    longhorn.io/data-locality: "strict-local"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
